### YamlMime:ManagedReference
items:
- uid: Application.Dto.TodoTaskDto.TodoTaskShortDto
  commentId: T:Application.Dto.TodoTaskDto.TodoTaskShortDto
  id: TodoTaskDto.TodoTaskShortDto
  parent: Application.Dto
  children:
  - Application.Dto.TodoTaskDto.TodoTaskShortDto.#ctor(System.Guid,System.String,System.Nullable{System.DateTime})
  - Application.Dto.TodoTaskDto.TodoTaskShortDto.Deadline
  - Application.Dto.TodoTaskDto.TodoTaskShortDto.Name
  - Application.Dto.TodoTaskDto.TodoTaskShortDto.TaskId
  langs:
  - csharp
  - vb
  name: TodoTaskDto.TodoTaskShortDto
  nameWithType: TodoTaskDto.TodoTaskShortDto
  fullName: Application.Dto.TodoTaskDto.TodoTaskShortDto
  type: Class
  source:
    remote:
      path: program/Application/Dto/TodoTaskDto.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: TodoTaskShortDto
    path: ../Application/Dto/TodoTaskDto.cs
    startLine: 28
  assemblies:
  - Application
  namespace: Application.Dto
  syntax:
    content: 'public record TodoTaskDto.TodoTaskShortDto : IEquatable<TodoTaskDto.TodoTaskShortDto>'
    content.vb: Public Class TodoTaskDto.TodoTaskShortDto Implements IEquatable(Of TodoTaskDto.TodoTaskShortDto)
  inheritance:
  - System.Object
  implements:
  - System.IEquatable{Application.Dto.TodoTaskDto.TodoTaskShortDto}
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Application.Dto.TodoTaskDto.TodoTaskShortDto.#ctor(System.Guid,System.String,System.Nullable{System.DateTime})
  commentId: M:Application.Dto.TodoTaskDto.TodoTaskShortDto.#ctor(System.Guid,System.String,System.Nullable{System.DateTime})
  id: '#ctor(System.Guid,System.String,System.Nullable{System.DateTime})'
  parent: Application.Dto.TodoTaskDto.TodoTaskShortDto
  langs:
  - csharp
  - vb
  name: TodoTaskShortDto(Guid, string, DateTime?)
  nameWithType: TodoTaskDto.TodoTaskShortDto.TodoTaskShortDto(Guid, string, DateTime?)
  fullName: Application.Dto.TodoTaskDto.TodoTaskShortDto.TodoTaskShortDto(System.Guid, string, System.DateTime?)
  type: Constructor
  source:
    remote:
      path: program/Application/Dto/TodoTaskDto.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: .ctor
    path: ../Application/Dto/TodoTaskDto.cs
    startLine: 28
  assemblies:
  - Application
  namespace: Application.Dto
  syntax:
    content: public TodoTaskShortDto(Guid TaskId, string Name, DateTime? Deadline)
    parameters:
    - id: TaskId
      type: System.Guid
    - id: Name
      type: System.String
    - id: Deadline
      type: System.Nullable{System.DateTime}
    content.vb: Public Sub New(TaskId As Guid, Name As String, Deadline As Date?)
  overload: Application.Dto.TodoTaskDto.TodoTaskShortDto.#ctor*
  nameWithType.vb: TodoTaskDto.TodoTaskShortDto.New(Guid, String, Date?)
  fullName.vb: Application.Dto.TodoTaskDto.TodoTaskShortDto.New(System.Guid, String, Date?)
  name.vb: New(Guid, String, Date?)
- uid: Application.Dto.TodoTaskDto.TodoTaskShortDto.TaskId
  commentId: P:Application.Dto.TodoTaskDto.TodoTaskShortDto.TaskId
  id: TaskId
  parent: Application.Dto.TodoTaskDto.TodoTaskShortDto
  langs:
  - csharp
  - vb
  name: TaskId
  nameWithType: TodoTaskDto.TodoTaskShortDto.TaskId
  fullName: Application.Dto.TodoTaskDto.TodoTaskShortDto.TaskId
  type: Property
  source:
    remote:
      path: program/Application/Dto/TodoTaskDto.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: TaskId
    path: ../Application/Dto/TodoTaskDto.cs
    startLine: 29
  assemblies:
  - Application
  namespace: Application.Dto
  syntax:
    content: public Guid TaskId { get; init; }
    parameters: []
    return:
      type: System.Guid
    content.vb: Public Property TaskId As Guid
  overload: Application.Dto.TodoTaskDto.TodoTaskShortDto.TaskId*
- uid: Application.Dto.TodoTaskDto.TodoTaskShortDto.Name
  commentId: P:Application.Dto.TodoTaskDto.TodoTaskShortDto.Name
  id: Name
  parent: Application.Dto.TodoTaskDto.TodoTaskShortDto
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: TodoTaskDto.TodoTaskShortDto.Name
  fullName: Application.Dto.TodoTaskDto.TodoTaskShortDto.Name
  type: Property
  source:
    remote:
      path: program/Application/Dto/TodoTaskDto.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: Name
    path: ../Application/Dto/TodoTaskDto.cs
    startLine: 30
  assemblies:
  - Application
  namespace: Application.Dto
  syntax:
    content: public string Name { get; init; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: Application.Dto.TodoTaskDto.TodoTaskShortDto.Name*
- uid: Application.Dto.TodoTaskDto.TodoTaskShortDto.Deadline
  commentId: P:Application.Dto.TodoTaskDto.TodoTaskShortDto.Deadline
  id: Deadline
  parent: Application.Dto.TodoTaskDto.TodoTaskShortDto
  langs:
  - csharp
  - vb
  name: Deadline
  nameWithType: TodoTaskDto.TodoTaskShortDto.Deadline
  fullName: Application.Dto.TodoTaskDto.TodoTaskShortDto.Deadline
  type: Property
  source:
    remote:
      path: program/Application/Dto/TodoTaskDto.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: Deadline
    path: ../Application/Dto/TodoTaskDto.cs
    startLine: 31
  assemblies:
  - Application
  namespace: Application.Dto
  syntax:
    content: public DateTime? Deadline { get; init; }
    parameters: []
    return:
      type: System.Nullable{System.DateTime}
    content.vb: Public Property Deadline As Date?
  overload: Application.Dto.TodoTaskDto.TodoTaskShortDto.Deadline*
references:
- uid: Application.Dto
  commentId: N:Application.Dto
  href: Application.html
  name: Application.Dto
  nameWithType: Application.Dto
  fullName: Application.Dto
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Dto
    name: Dto
    href: Application.Dto.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Dto
    name: Dto
    href: Application.Dto.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.IEquatable{Application.Dto.TodoTaskDto.TodoTaskShortDto}
  commentId: T:System.IEquatable{Application.Dto.TodoTaskDto.TodoTaskShortDto}
  parent: System
  definition: System.IEquatable`1
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<TodoTaskDto.TodoTaskShortDto>
  nameWithType: IEquatable<TodoTaskDto.TodoTaskShortDto>
  fullName: System.IEquatable<Application.Dto.TodoTaskDto.TodoTaskShortDto>
  nameWithType.vb: IEquatable(Of TodoTaskDto.TodoTaskShortDto)
  fullName.vb: System.IEquatable(Of Application.Dto.TodoTaskDto.TodoTaskShortDto)
  name.vb: IEquatable(Of TodoTaskDto.TodoTaskShortDto)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - uid: Application.Dto.TodoTaskDto
    name: TodoTaskDto
    href: Application.Dto.TodoTaskDto.html
  - name: .
  - uid: Application.Dto.TodoTaskDto.TodoTaskShortDto
    name: TodoTaskShortDto
    href: Application.Dto.TodoTaskDto.TodoTaskShortDto.html
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - uid: Application.Dto.TodoTaskDto
    name: TodoTaskDto
    href: Application.Dto.TodoTaskDto.html
  - name: .
  - uid: Application.Dto.TodoTaskDto.TodoTaskShortDto
    name: TodoTaskShortDto
    href: Application.Dto.TodoTaskDto.TodoTaskShortDto.html
  - name: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.IEquatable`1
  commentId: T:System.IEquatable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  name: IEquatable<T>
  nameWithType: IEquatable<T>
  fullName: System.IEquatable<T>
  nameWithType.vb: IEquatable(Of T)
  fullName.vb: System.IEquatable(Of T)
  name.vb: IEquatable(Of T)
  spec.csharp:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.IEquatable`1
    name: IEquatable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.iequatable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Application.Dto.TodoTaskDto.TodoTaskShortDto.#ctor*
  commentId: Overload:Application.Dto.TodoTaskDto.TodoTaskShortDto.#ctor
  href: Application.Dto.TodoTaskDto.TodoTaskShortDto.html#Application_Dto_TodoTaskDto_TodoTaskShortDto__ctor_System_Guid_System_String_System_Nullable_System_DateTime__
  name: TodoTaskShortDto
  nameWithType: TodoTaskDto.TodoTaskShortDto.TodoTaskShortDto
  fullName: Application.Dto.TodoTaskDto.TodoTaskShortDto.TodoTaskShortDto
  nameWithType.vb: TodoTaskDto.TodoTaskShortDto.New
  fullName.vb: Application.Dto.TodoTaskDto.TodoTaskShortDto.New
  name.vb: New
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.guid
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Nullable{System.DateTime}
  commentId: T:System.Nullable{System.DateTime}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.datetime
  name: DateTime?
  nameWithType: DateTime?
  fullName: System.DateTime?
  nameWithType.vb: Date?
  fullName.vb: Date?
  name.vb: Date?
  spec.csharp:
  - uid: System.DateTime
    name: DateTime
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: '?'
  spec.vb:
  - uid: System.DateTime
    name: Date
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.datetime
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Application.Dto.TodoTaskDto.TodoTaskShortDto.TaskId*
  commentId: Overload:Application.Dto.TodoTaskDto.TodoTaskShortDto.TaskId
  href: Application.Dto.TodoTaskDto.TodoTaskShortDto.html#Application_Dto_TodoTaskDto_TodoTaskShortDto_TaskId
  name: TaskId
  nameWithType: TodoTaskDto.TodoTaskShortDto.TaskId
  fullName: Application.Dto.TodoTaskDto.TodoTaskShortDto.TaskId
- uid: Application.Dto.TodoTaskDto.TodoTaskShortDto.Name*
  commentId: Overload:Application.Dto.TodoTaskDto.TodoTaskShortDto.Name
  href: Application.Dto.TodoTaskDto.TodoTaskShortDto.html#Application_Dto_TodoTaskDto_TodoTaskShortDto_Name
  name: Name
  nameWithType: TodoTaskDto.TodoTaskShortDto.Name
  fullName: Application.Dto.TodoTaskDto.TodoTaskShortDto.Name
- uid: Application.Dto.TodoTaskDto.TodoTaskShortDto.Deadline*
  commentId: Overload:Application.Dto.TodoTaskDto.TodoTaskShortDto.Deadline
  href: Application.Dto.TodoTaskDto.TodoTaskShortDto.html#Application_Dto_TodoTaskDto_TodoTaskShortDto_Deadline
  name: Deadline
  nameWithType: TodoTaskDto.TodoTaskShortDto.Deadline
  fullName: Application.Dto.TodoTaskDto.TodoTaskShortDto.Deadline
