### YamlMime:ManagedReference
items:
- uid: Application.Interfaces.Command.ICommandUseCase
  commentId: T:Application.Interfaces.Command.ICommandUseCase
  id: ICommandUseCase
  parent: Application.Interfaces.Command
  children: []
  langs:
  - csharp
  - vb
  name: ICommandUseCase
  nameWithType: ICommandUseCase
  fullName: Application.Interfaces.Command.ICommandUseCase
  type: Interface
  source:
    remote:
      path: program/Application/Interfaces/Command/ICommandUseCase.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: ICommandUseCase
    path: ../Application/Interfaces/Command/ICommandUseCase.cs
    startLine: 6
  assemblies:
  - Application
  namespace: Application.Interfaces.Command
  summary: >-
    Интерфейс для command use case (добавление, обновление, удаление).

    Command операции изменяют состояние системы и возвращают количество затронутых записей.
  example: []
  syntax:
    content: 'public interface ICommandUseCase : IOperation<int>'
    content.vb: Public Interface ICommandUseCase Inherits IOperation(Of Integer)
  inheritedMembers:
  - Application.Interfaces.Command.IOperation{System.Int32}.Execute
references:
- uid: Application.Interfaces.Command
  commentId: N:Application.Interfaces.Command
  href: Application.html
  name: Application.Interfaces.Command
  nameWithType: Application.Interfaces.Command
  fullName: Application.Interfaces.Command
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  - name: .
  - uid: Application.Interfaces.Command
    name: Command
    href: Application.Interfaces.Command.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  - name: .
  - uid: Application.Interfaces.Command
    name: Command
    href: Application.Interfaces.Command.html
- uid: Application.Interfaces.Command.IOperation{System.Int32}.Execute
  commentId: M:Application.Interfaces.Command.IOperation{System.Int32}.Execute
  parent: Application.Interfaces.Command.IOperation{System.Int32}
  definition: Application.Interfaces.Command.IOperation`1.Execute
  href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  name: Execute()
  nameWithType: IOperation<int>.Execute()
  fullName: Application.Interfaces.Command.IOperation<int>.Execute()
  nameWithType.vb: IOperation(Of Integer).Execute()
  fullName.vb: Application.Interfaces.Command.IOperation(Of Integer).Execute()
  spec.csharp:
  - uid: Application.Interfaces.Command.IOperation{System.Int32}.Execute
    name: Execute
    href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  - name: (
  - name: )
  spec.vb:
  - uid: Application.Interfaces.Command.IOperation{System.Int32}.Execute
    name: Execute
    href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  - name: (
  - name: )
- uid: Application.Interfaces.Command.IOperation`1.Execute
  commentId: M:Application.Interfaces.Command.IOperation`1.Execute
  href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  name: Execute()
  nameWithType: IOperation<TResult>.Execute()
  fullName: Application.Interfaces.Command.IOperation<TResult>.Execute()
  nameWithType.vb: IOperation(Of TResult).Execute()
  fullName.vb: Application.Interfaces.Command.IOperation(Of TResult).Execute()
  spec.csharp:
  - uid: Application.Interfaces.Command.IOperation`1.Execute
    name: Execute
    href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  - name: (
  - name: )
  spec.vb:
  - uid: Application.Interfaces.Command.IOperation`1.Execute
    name: Execute
    href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  - name: (
  - name: )
- uid: Application.Interfaces.Command.IOperation{System.Int32}
  commentId: T:Application.Interfaces.Command.IOperation{System.Int32}
  parent: Application.Interfaces.Command
  definition: Application.Interfaces.Command.IOperation`1
  href: Application.Interfaces.Command.IOperation-1.html
  name: IOperation<int>
  nameWithType: IOperation<int>
  fullName: Application.Interfaces.Command.IOperation<int>
  nameWithType.vb: IOperation(Of Integer)
  fullName.vb: Application.Interfaces.Command.IOperation(Of Integer)
  name.vb: IOperation(Of Integer)
  spec.csharp:
  - uid: Application.Interfaces.Command.IOperation`1
    name: IOperation
    href: Application.Interfaces.Command.IOperation-1.html
  - name: <
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: '>'
  spec.vb:
  - uid: Application.Interfaces.Command.IOperation`1
    name: IOperation
    href: Application.Interfaces.Command.IOperation-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: Application.Interfaces.Command.IOperation`1
  commentId: T:Application.Interfaces.Command.IOperation`1
  href: Application.Interfaces.Command.IOperation-1.html
  name: IOperation<TResult>
  nameWithType: IOperation<TResult>
  fullName: Application.Interfaces.Command.IOperation<TResult>
  nameWithType.vb: IOperation(Of TResult)
  fullName.vb: Application.Interfaces.Command.IOperation(Of TResult)
  name.vb: IOperation(Of TResult)
  spec.csharp:
  - uid: Application.Interfaces.Command.IOperation`1
    name: IOperation
    href: Application.Interfaces.Command.IOperation-1.html
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: Application.Interfaces.Command.IOperation`1
    name: IOperation
    href: Application.Interfaces.Command.IOperation-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
