### YamlMime:ManagedReference
items:
- uid: Application.Interfaces.IPasswordHasher
  commentId: T:Application.Interfaces.IPasswordHasher
  id: IPasswordHasher
  parent: Application.Interfaces
  children:
  - Application.Interfaces.IPasswordHasher.HashedAsync(System.String)
  - Application.Interfaces.IPasswordHasher.VerifyAsync(System.String,System.String)
  langs:
  - csharp
  - vb
  name: IPasswordHasher
  nameWithType: IPasswordHasher
  fullName: Application.Interfaces.IPasswordHasher
  type: Interface
  source:
    remote:
      path: program/Application/Interfaces/IPasswordHasher.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: IPasswordHasher
    path: ../Application/Interfaces/IPasswordHasher.cs
    startLine: 2
  assemblies:
  - Application
  namespace: Application.Interfaces
  syntax:
    content: public interface IPasswordHasher
    content.vb: Public Interface IPasswordHasher
- uid: Application.Interfaces.IPasswordHasher.HashedAsync(System.String)
  commentId: M:Application.Interfaces.IPasswordHasher.HashedAsync(System.String)
  id: HashedAsync(System.String)
  parent: Application.Interfaces.IPasswordHasher
  langs:
  - csharp
  - vb
  name: HashedAsync(string)
  nameWithType: IPasswordHasher.HashedAsync(string)
  fullName: Application.Interfaces.IPasswordHasher.HashedAsync(string)
  type: Method
  source:
    remote:
      path: program/Application/Interfaces/IPasswordHasher.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: HashedAsync
    path: ../Application/Interfaces/IPasswordHasher.cs
    startLine: 4
  assemblies:
  - Application
  namespace: Application.Interfaces
  syntax:
    content: Task<string> HashedAsync(string password)
    parameters:
    - id: password
      type: System.String
    return:
      type: System.Threading.Tasks.Task{System.String}
    content.vb: Function HashedAsync(password As String) As Task(Of String)
  overload: Application.Interfaces.IPasswordHasher.HashedAsync*
  nameWithType.vb: IPasswordHasher.HashedAsync(String)
  fullName.vb: Application.Interfaces.IPasswordHasher.HashedAsync(String)
  name.vb: HashedAsync(String)
- uid: Application.Interfaces.IPasswordHasher.VerifyAsync(System.String,System.String)
  commentId: M:Application.Interfaces.IPasswordHasher.VerifyAsync(System.String,System.String)
  id: VerifyAsync(System.String,System.String)
  parent: Application.Interfaces.IPasswordHasher
  langs:
  - csharp
  - vb
  name: VerifyAsync(string, string)
  nameWithType: IPasswordHasher.VerifyAsync(string, string)
  fullName: Application.Interfaces.IPasswordHasher.VerifyAsync(string, string)
  type: Method
  source:
    remote:
      path: program/Application/Interfaces/IPasswordHasher.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: VerifyAsync
    path: ../Application/Interfaces/IPasswordHasher.cs
    startLine: 5
  assemblies:
  - Application
  namespace: Application.Interfaces
  syntax:
    content: Task<bool> VerifyAsync(string password, string hashedPassword)
    parameters:
    - id: password
      type: System.String
    - id: hashedPassword
      type: System.String
    return:
      type: System.Threading.Tasks.Task{System.Boolean}
    content.vb: Function VerifyAsync(password As String, hashedPassword As String) As Task(Of Boolean)
  overload: Application.Interfaces.IPasswordHasher.VerifyAsync*
  nameWithType.vb: IPasswordHasher.VerifyAsync(String, String)
  fullName.vb: Application.Interfaces.IPasswordHasher.VerifyAsync(String, String)
  name.vb: VerifyAsync(String, String)
references:
- uid: Application.Interfaces
  commentId: N:Application.Interfaces
  href: Application.html
  name: Application.Interfaces
  nameWithType: Application.Interfaces
  fullName: Application.Interfaces
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
- uid: Application.Interfaces.IPasswordHasher.HashedAsync*
  commentId: Overload:Application.Interfaces.IPasswordHasher.HashedAsync
  href: Application.Interfaces.IPasswordHasher.html#Application_Interfaces_IPasswordHasher_HashedAsync_System_String_
  name: HashedAsync
  nameWithType: IPasswordHasher.HashedAsync
  fullName: Application.Interfaces.IPasswordHasher.HashedAsync
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: System.Threading.Tasks.Task{System.String}
  commentId: T:System.Threading.Tasks.Task{System.String}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<string>
  nameWithType: Task<string>
  fullName: System.Threading.Tasks.Task<string>
  nameWithType.vb: Task(Of String)
  fullName.vb: System.Threading.Tasks.Task(Of String)
  name.vb: Task(Of String)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: System.String
    name: string
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.String
    name: String
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.string
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
- uid: Application.Interfaces.IPasswordHasher.VerifyAsync*
  commentId: Overload:Application.Interfaces.IPasswordHasher.VerifyAsync
  href: Application.Interfaces.IPasswordHasher.html#Application_Interfaces_IPasswordHasher_VerifyAsync_System_String_System_String_
  name: VerifyAsync
  nameWithType: IPasswordHasher.VerifyAsync
  fullName: Application.Interfaces.IPasswordHasher.VerifyAsync
- uid: System.Threading.Tasks.Task{System.Boolean}
  commentId: T:System.Threading.Tasks.Task{System.Boolean}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<bool>
  nameWithType: Task<bool>
  fullName: System.Threading.Tasks.Task<bool>
  nameWithType.vb: Task(Of Boolean)
  fullName.vb: System.Threading.Tasks.Task(Of Boolean)
  name.vb: Task(Of Boolean)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: System.Boolean
    name: bool
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.boolean
  - name: )
