### YamlMime:ManagedReference
items:
- uid: Application.UseCase.TodoTaskUseCases
  commentId: N:Application.UseCase.TodoTaskUseCases
  id: Application.UseCase.TodoTaskUseCases
  children:
  - Application.UseCase.TodoTaskUseCases.AddNewTaskUseCase
  - Application.UseCase.TodoTaskUseCases.DeletionTaskUseCase
  - Application.UseCase.TodoTaskUseCases.UpdateTaskUseCase
  langs:
  - csharp
  - vb
  name: Application.UseCase.TodoTaskUseCases
  nameWithType: Application.UseCase.TodoTaskUseCases
  fullName: Application.UseCase.TodoTaskUseCases
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.UseCase.TodoTaskUseCases.AddNewTaskUseCase
  commentId: T:Application.UseCase.TodoTaskUseCases.AddNewTaskUseCase
  href: Application.UseCase.TodoTaskUseCases.AddNewTaskUseCase.html
  name: AddNewTaskUseCase
  nameWithType: AddNewTaskUseCase
  fullName: Application.UseCase.TodoTaskUseCases.AddNewTaskUseCase
- uid: Application.UseCase.TodoTaskUseCases.DeletionTaskUseCase
  commentId: T:Application.UseCase.TodoTaskUseCases.DeletionTaskUseCase
  href: Application.UseCase.TodoTaskUseCases.DeletionTaskUseCase.html
  name: DeletionTaskUseCase
  nameWithType: DeletionTaskUseCase
  fullName: Application.UseCase.TodoTaskUseCases.DeletionTaskUseCase
- uid: Application.UseCase.TodoTaskUseCases.UpdateTaskUseCase
  commentId: T:Application.UseCase.TodoTaskUseCases.UpdateTaskUseCase
  href: Application.UseCase.TodoTaskUseCases.UpdateTaskUseCase.html
  name: UpdateTaskUseCase
  nameWithType: UpdateTaskUseCase
  fullName: Application.UseCase.TodoTaskUseCases.UpdateTaskUseCase
