### YamlMime:ManagedReference
items:
- uid: Application.Interfaces.Command.ICommandWithUndo
  commentId: T:Application.Interfaces.Command.ICommandWithUndo
  id: ICommandWithUndo
  parent: Application.Interfaces.Command
  children:
  - Application.Interfaces.Command.ICommandWithUndo.Undo
  langs:
  - csharp
  - vb
  name: ICommandWithUndo
  nameWithType: ICommandWithUndo
  fullName: Application.Interfaces.Command.ICommandWithUndo
  type: Interface
  source:
    remote:
      path: program/Application/Interfaces/Command/ICommandWithUndo.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: ICommandWithUndo
    path: ../Application/Interfaces/Command/ICommandWithUndo.cs
    startLine: 5
  assemblies:
  - Application
  namespace: Application.Interfaces.Command
  summary: Интерфейс для command use case с поддержкой отмены операции.
  example: []
  syntax:
    content: 'public interface ICommandWithUndo : ICommandUseCase, IOperation<int>'
    content.vb: Public Interface ICommandWithUndo Inherits ICommandUseCase, IOperation(Of Integer)
  inheritedMembers:
  - Application.Interfaces.Command.IOperation{System.Int32}.Execute
- uid: Application.Interfaces.Command.ICommandWithUndo.Undo
  commentId: M:Application.Interfaces.Command.ICommandWithUndo.Undo
  id: Undo
  parent: Application.Interfaces.Command.ICommandWithUndo
  langs:
  - csharp
  - vb
  name: Undo()
  nameWithType: ICommandWithUndo.Undo()
  fullName: Application.Interfaces.Command.ICommandWithUndo.Undo()
  type: Method
  source:
    remote:
      path: program/Application/Interfaces/Command/ICommandWithUndo.cs
      branch: Clean-Architecture
      repo: https://github.com/PoneMaurice/RKIS-2025-2026.git
    id: Undo
    path: ../Application/Interfaces/Command/ICommandWithUndo.cs
    startLine: 11
  assemblies:
  - Application
  namespace: Application.Interfaces.Command
  summary: Отменяет выполненную операцию.
  example: []
  syntax:
    content: Task<int> Undo()
    return:
      type: System.Threading.Tasks.Task{System.Int32}
      description: Количество затронутых записей при отмене.
    content.vb: Function Undo() As Task(Of Integer)
  overload: Application.Interfaces.Command.ICommandWithUndo.Undo*
references:
- uid: Application.Interfaces.Command
  commentId: N:Application.Interfaces.Command
  href: Application.html
  name: Application.Interfaces.Command
  nameWithType: Application.Interfaces.Command
  fullName: Application.Interfaces.Command
  spec.csharp:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  - name: .
  - uid: Application.Interfaces.Command
    name: Command
    href: Application.Interfaces.Command.html
  spec.vb:
  - uid: Application
    name: Application
    href: Application.html
  - name: .
  - uid: Application.Interfaces
    name: Interfaces
    href: Application.Interfaces.html
  - name: .
  - uid: Application.Interfaces.Command
    name: Command
    href: Application.Interfaces.Command.html
- uid: Application.Interfaces.Command.IOperation{System.Int32}.Execute
  commentId: M:Application.Interfaces.Command.IOperation{System.Int32}.Execute
  parent: Application.Interfaces.Command.IOperation{System.Int32}
  definition: Application.Interfaces.Command.IOperation`1.Execute
  href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  name: Execute()
  nameWithType: IOperation<int>.Execute()
  fullName: Application.Interfaces.Command.IOperation<int>.Execute()
  nameWithType.vb: IOperation(Of Integer).Execute()
  fullName.vb: Application.Interfaces.Command.IOperation(Of Integer).Execute()
  spec.csharp:
  - uid: Application.Interfaces.Command.IOperation{System.Int32}.Execute
    name: Execute
    href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  - name: (
  - name: )
  spec.vb:
  - uid: Application.Interfaces.Command.IOperation{System.Int32}.Execute
    name: Execute
    href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  - name: (
  - name: )
- uid: Application.Interfaces.Command.IOperation`1.Execute
  commentId: M:Application.Interfaces.Command.IOperation`1.Execute
  href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  name: Execute()
  nameWithType: IOperation<TResult>.Execute()
  fullName: Application.Interfaces.Command.IOperation<TResult>.Execute()
  nameWithType.vb: IOperation(Of TResult).Execute()
  fullName.vb: Application.Interfaces.Command.IOperation(Of TResult).Execute()
  spec.csharp:
  - uid: Application.Interfaces.Command.IOperation`1.Execute
    name: Execute
    href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  - name: (
  - name: )
  spec.vb:
  - uid: Application.Interfaces.Command.IOperation`1.Execute
    name: Execute
    href: Application.Interfaces.Command.IOperation-1.html#Application_Interfaces_Command_IOperation_1_Execute
  - name: (
  - name: )
- uid: Application.Interfaces.Command.IOperation{System.Int32}
  commentId: T:Application.Interfaces.Command.IOperation{System.Int32}
  parent: Application.Interfaces.Command
  definition: Application.Interfaces.Command.IOperation`1
  href: Application.Interfaces.Command.IOperation-1.html
  name: IOperation<int>
  nameWithType: IOperation<int>
  fullName: Application.Interfaces.Command.IOperation<int>
  nameWithType.vb: IOperation(Of Integer)
  fullName.vb: Application.Interfaces.Command.IOperation(Of Integer)
  name.vb: IOperation(Of Integer)
  spec.csharp:
  - uid: Application.Interfaces.Command.IOperation`1
    name: IOperation
    href: Application.Interfaces.Command.IOperation-1.html
  - name: <
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: '>'
  spec.vb:
  - uid: Application.Interfaces.Command.IOperation`1
    name: IOperation
    href: Application.Interfaces.Command.IOperation-1.html
  - name: (
  - name: Of
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: Application.Interfaces.Command.IOperation`1
  commentId: T:Application.Interfaces.Command.IOperation`1
  href: Application.Interfaces.Command.IOperation-1.html
  name: IOperation<TResult>
  nameWithType: IOperation<TResult>
  fullName: Application.Interfaces.Command.IOperation<TResult>
  nameWithType.vb: IOperation(Of TResult)
  fullName.vb: Application.Interfaces.Command.IOperation(Of TResult)
  name.vb: IOperation(Of TResult)
  spec.csharp:
  - uid: Application.Interfaces.Command.IOperation`1
    name: IOperation
    href: Application.Interfaces.Command.IOperation-1.html
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: Application.Interfaces.Command.IOperation`1
    name: IOperation
    href: Application.Interfaces.Command.IOperation-1.html
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: Application.Interfaces.Command.ICommandWithUndo.Undo*
  commentId: Overload:Application.Interfaces.Command.ICommandWithUndo.Undo
  href: Application.Interfaces.Command.ICommandWithUndo.html#Application_Interfaces_Command_ICommandWithUndo_Undo
  name: Undo
  nameWithType: ICommandWithUndo.Undo
  fullName: Application.Interfaces.Command.ICommandWithUndo.Undo
- uid: System.Threading.Tasks.Task{System.Int32}
  commentId: T:System.Threading.Tasks.Task{System.Int32}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<int>
  nameWithType: Task<int>
  fullName: System.Threading.Tasks.Task<int>
  nameWithType.vb: Task(Of Integer)
  fullName.vb: System.Threading.Tasks.Task(Of Integer)
  name.vb: Task(Of Integer)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: )
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: <
  - name: TResult
  - name: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task-1
  - name: (
  - name: Of
  - name: " "
  - name: TResult
  - name: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
