### YamlMime:ManagedReference
items:
- uid: Application.UseCase.ProfileUseCases
  commentId: N:Application.UseCase.ProfileUseCases
  id: Application.UseCase.ProfileUseCases
  children:
  - Application.UseCase.ProfileUseCases.AddNewProfileUseCase
  - Application.UseCase.ProfileUseCases.ChangeProfileUseCase
  - Application.UseCase.ProfileUseCases.CheckProfileExistsUseCase
  - Application.UseCase.ProfileUseCases.CountProfilesUseCase
  - Application.UseCase.ProfileUseCases.DeletionProfileUseCase
  - Application.UseCase.ProfileUseCases.FindProfilesUseCase
  - Application.UseCase.ProfileUseCases.GetAllProfilesUseCase
  - Application.UseCase.ProfileUseCases.GetProfileUseCase
  - Application.UseCase.ProfileUseCases.UpdateProfileUseCase
  langs:
  - csharp
  - vb
  name: Application.UseCase.ProfileUseCases
  nameWithType: Application.UseCase.ProfileUseCases
  fullName: Application.UseCase.ProfileUseCases
  type: Namespace
  assemblies:
  - Application
references:
- uid: Application.UseCase.ProfileUseCases.AddNewProfileUseCase
  commentId: T:Application.UseCase.ProfileUseCases.AddNewProfileUseCase
  href: Application.UseCase.ProfileUseCases.AddNewProfileUseCase.html
  name: AddNewProfileUseCase
  nameWithType: AddNewProfileUseCase
  fullName: Application.UseCase.ProfileUseCases.AddNewProfileUseCase
- uid: Application.UseCase.ProfileUseCases.ChangeProfileUseCase
  commentId: T:Application.UseCase.ProfileUseCases.ChangeProfileUseCase
  href: Application.UseCase.ProfileUseCases.ChangeProfileUseCase.html
  name: ChangeProfileUseCase
  nameWithType: ChangeProfileUseCase
  fullName: Application.UseCase.ProfileUseCases.ChangeProfileUseCase
- uid: Application.UseCase.ProfileUseCases.CheckProfileExistsUseCase
  commentId: T:Application.UseCase.ProfileUseCases.CheckProfileExistsUseCase
  href: Application.UseCase.ProfileUseCases.CheckProfileExistsUseCase.html
  name: CheckProfileExistsUseCase
  nameWithType: CheckProfileExistsUseCase
  fullName: Application.UseCase.ProfileUseCases.CheckProfileExistsUseCase
- uid: Application.UseCase.ProfileUseCases.CountProfilesUseCase
  commentId: T:Application.UseCase.ProfileUseCases.CountProfilesUseCase
  href: Application.UseCase.ProfileUseCases.CountProfilesUseCase.html
  name: CountProfilesUseCase
  nameWithType: CountProfilesUseCase
  fullName: Application.UseCase.ProfileUseCases.CountProfilesUseCase
- uid: Application.UseCase.ProfileUseCases.DeletionProfileUseCase
  commentId: T:Application.UseCase.ProfileUseCases.DeletionProfileUseCase
  href: Application.UseCase.ProfileUseCases.DeletionProfileUseCase.html
  name: DeletionProfileUseCase
  nameWithType: DeletionProfileUseCase
  fullName: Application.UseCase.ProfileUseCases.DeletionProfileUseCase
- uid: Application.UseCase.ProfileUseCases.FindProfilesUseCase
  commentId: T:Application.UseCase.ProfileUseCases.FindProfilesUseCase
  href: Application.UseCase.ProfileUseCases.FindProfilesUseCase.html
  name: FindProfilesUseCase
  nameWithType: FindProfilesUseCase
  fullName: Application.UseCase.ProfileUseCases.FindProfilesUseCase
- uid: Application.UseCase.ProfileUseCases.GetAllProfilesUseCase
  commentId: T:Application.UseCase.ProfileUseCases.GetAllProfilesUseCase
  href: Application.UseCase.ProfileUseCases.GetAllProfilesUseCase.html
  name: GetAllProfilesUseCase
  nameWithType: GetAllProfilesUseCase
  fullName: Application.UseCase.ProfileUseCases.GetAllProfilesUseCase
- uid: Application.UseCase.ProfileUseCases.GetProfileUseCase
  commentId: T:Application.UseCase.ProfileUseCases.GetProfileUseCase
  href: Application.UseCase.ProfileUseCases.GetProfileUseCase.html
  name: GetProfileUseCase
  nameWithType: GetProfileUseCase
  fullName: Application.UseCase.ProfileUseCases.GetProfileUseCase
- uid: Application.UseCase.ProfileUseCases.UpdateProfileUseCase
  commentId: T:Application.UseCase.ProfileUseCases.UpdateProfileUseCase
  href: Application.UseCase.ProfileUseCases.UpdateProfileUseCase.html
  name: UpdateProfileUseCase
  nameWithType: UpdateProfileUseCase
  fullName: Application.UseCase.ProfileUseCases.UpdateProfileUseCase
